SELECT * FROM EMPLOYEERS;
SELECT * FROM EMPLOYEERS WHERE FIRST_NAME='David';
SELECT * FROM EMPLOYEERS WHERE DEPARTMENT_ID=20 OR DEPARTMENT_ID=30;
SELECT * FROM EMPLOYEERS WHERE DEPARTMENT_ID=50 OR DEPARTMENT_ID=80 AND COMMISION_PCT IS NOT NULL;
SELECT * FROM EMPLOYEERS WHERE HIRE_DATE LIKE '01-%';
SELECT * FROM EMPLOYEERS WHERE HIRE_DATE LIKE '%-2008';
SELECT CONCAT('Tomorrow is ', DATE_FORMAT(DATE_ADD(NOW(), INTERVAL 1 DAY), '%D day of %M')) AS TOMORROW_DATE FROM DUAL;
SELECT FIRST_NAME,SECOND_NAME,CONCAT(DATE_FORMAT(hire_date, '%D 'st of %M, %Y')) AS HIRE_DATE_FORMAT FROM employees;
SELECT CONCAT(FORMAT((SALARY * 1.2), 1),'$ ') AS INCRESED_SALARY FROM employees;
SELECT * FROM EMPLOYEERS WHERE HIRE_DATE LIKE '%-02-2007';
SELECT NOW(), DATE_ADD(NOW(), INTERVAL 1 SECOND), DATE_ADD(NOW(), INTERVAL 1 MINUTE), DATE_ADD(NOW(), INTERVAL 1 HOUR), DATE_ADD(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 1 MONTH), DATE_ADD(NOW(), INTERVAL 1 YEAR) FROM DUAL;
SELECT FIRST_NAME,LAST_NAME, CONCAT('$',FORMAT(SALARY+(SALARY*(1+COMMISSION_PCT)),2))
SELECT CONCAT(CASE WHEN COMMISSION_PCT IS NULL THEN 'No' ELSE 'Yes' END) AS BONUS FROM EMPLOYEES;
